get:
  tags:
    - Application
  summary: Finds living applications
  description: |
    ![edition](https://img.shields.io/badge/edition-entreprise-blue) ![edition](https://img.shields.io/badge/edition-community-brightgreen)

    Finds living applications with pagination params and filters

    - can order on `id`,`creationDate`, `createdBy`, `profileId`, `token`, `displayName`, `updatedBy`, `lastUpdateDate`, `version`
    - can search on `token`, `displayName`, `version`
    - can filter on `token`, `displayName`, `version`, `profileId`, `creationDate`, `createdBy`, `updatedBy` , `lastUpdateDate`

  operationId: findApplications
  parameters:
    - $ref: '../components/parameters/pageIndex.yaml'
    - $ref: '../components/parameters/pageCount.yaml'
    - $ref: '../components/parameters/pageFilter.yaml'
    - $ref: '../components/parameters/pageOrder.yaml'
    - $ref: '../components/parameters/pageSearch.yaml'
  responses:
    '200':
      description: successful operation
      headers:
        Content-Range:
          schema:
            type: integer
            format: int64
          description: The total number of matching items
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/Application.yaml'
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'
post:
  tags:
    - Application
  summary: Create a living applications
  description: |
    ![edition](https://img.shields.io/badge/edition-entreprise-blue) ![edition](https://img.shields.io/badge/edition-community-brightgreen)

    Create a living applications
  operationId: createApplication
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            description:
              description: description of the application
              type: string
            displayName:
              description: display name of the application
              type: string
            profileId:
              description: profile authorized to access this application
              format: int64
              type: integer
            token:
              description: token of the application used to build the application URL
              type: string
            version:
              description: version of the application
              type: string
        example:
          version: "1.0"
          profileId: 2
          token: "myapp"
          displayName: "My app"
          description: "My application description"
    description: Partial living application description
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            items:
              $ref: '../components/schemas/Application.yaml'
            type: object
      description: successful operation
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'
  x-codegen-request-body-name: body