get:
  tags:
    - ApplicationMenu
  summary: Finds a application menu by ID
  description: |
    ![edition](https://img.shields.io/badge/edition-entreprise-blue)

    Returns a single application menu for the given ID
  operationId: geApplicationMenuById
  parameters:
    - description: ID of application menu to return
      in: path
      name: applicationMenuId
      required: true
      schema:
        format: int64
        type: integer
  responses:
    '200':
      description: sucessful operation
      content:
        application/json:
          schema:
            $ref: '../components/schemas/ApplicationMenu.yaml'
          example:
            id: 9823
            displayName: "menuLabel"
            applicationId: 1
            applicationPageId: 5
            menuIndex: 1
            parentMenuId: -1
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'

delete:
  tags:
    - ApplicationMenu
  summary: Delete an application menu by ID
  description: Delete a single application menu for the given ID
  operationId: deleteApplicationMenuById
  parameters:
    - description: ID of the application menu to delete
      in: path
      name: applicationMenuId
      required: true
      schema:
        format: int64
        type: integer
  responses:
    '200':
      description: sucessful operation
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'

put:
  tags:
    - ApplicationMenu
  summary: Update a application menu by ID
  description: Update a application menu for the given ID
  operationId: updateApplicationMenuById
  parameters:
    - description: ID of the application menu to return
      in: path
      name: applicationMenuId
      required: true
      schema:
        format: int64
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            displayName:
              description: display name of the application menu
              type: string
            applicationPageId:
              description: the application menu page ID
              type: integer
              format: int64
            menuIndex:
              description: the application menu index
              type: integer
              format: int32
            parentMenuId:
              description: the application parent menu ID
              type: integer
              format: int64
        example:
          displayName: "My updated label"
    description: Partial application menu description
    required: true
  responses:
    '200':
      $ref: '../components/responses/OK.yaml'
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'