post:
  tags:
    - Application
  summary: Upload a living application
  description: |
    ![edition](https://img.shields.io/badge/edition-entreprise-blue)

    Upload application
  operationId: uploadApplication
  requestBody:
    content:
      multipart/form-data:
        schema:
          type: object
          properties:
            file:
              type: string
              format: binary
  responses:
    '200':
      description: sucessful operation
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'