post:
  tags:
    - Application
  summary: Import a living application
  description: |
    ![edition](https://img.shields.io/badge/edition-entreprise-blue)

    Import a single application
  operationId: importApplication
  requestBody:
    content:
      application/x-www-form-urlencoded:
        schema:
          properties:
            applicationsDataUpload:
              type: string
              description: Uploaded file
            importPolicy:
              type: string
              description: Import policy
  responses:
    '200':
      description: sucessful operation
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'