version: '3'
services:

  nginx:
    build: nginx
    hostname: nginx
    ports:
      - "8084:80"

  swagger-ui:
    image: swaggerapi/swagger-ui
    hostname: swagger
    ports:
      - "8082:8080"
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./dist/openapi.yaml:/openapi/openapi.yaml

  redoc-ui:
    image: redocly/redoc
    hostname: redoc
    ports:
      - "8083:80"
    environment:
      - SPEC_URL=openapi.yaml
    volumes:
      - ./dist/openapi.yaml:/usr/share/nginx/html/openapi.yaml
      - ./dist/images/logo_bonitasoft_white.png:/usr/share/nginx/html/images/logo_bonitasoft_white.png
      - ./dist/images/rest_overview_v2.png:/usr/share/nginx/html/images/rest_overview_v2.png

  bonita:
    image: bonita:7.15.0
    hostname: bonita
    ports:
      - "8081:8080"
