version: '3'
services:

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "${TRAEFIK_PORT}:80"
      - "${TRAEFIK_ADMIN_PORT}:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  swagger-ui:
    image: swaggerapi/swagger-ui
    hostname: swagger
    labels:
#      - "traefik.enable=true"
      - "traefik.http.routers.swagger.rule=Host(`${SWAGGER_HOSTNAME}`)"
      - "traefik.http.services.swagger.loadbalancer.server.port=8080"
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./dist/openapi.yaml:/openapi/openapi.yaml

  redoc-ui:
    image: redocly/redoc
    hostname: redoc
    labels:
#      - "traefik.enable=true"
      - "traefik.http.routers.redoc.rule=Host(`redoc.localhost`)"
      - "traefik.http.services.redoc.loadbalancer.server.port=80"
    environment:
      - SPEC_URL=openapi.yaml
    volumes:
      - ./dist/openapi.yaml:/usr/share/nginx/html/openapi.yaml
      - ./dist/images/logo_bonitasoft_white.png:/usr/share/nginx/html/images/logo_bonitasoft_white.png
      - ./dist/images/rest_overview_v2.png:/usr/share/nginx/html/images/rest_overview_v2.png

  whoami:
    image: containous/whoami
    hostname: whoami
    expose:
      - 80
    deploy:
      labels:
#        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

  bonita:
    image: bonita:7.15.0
    hostname: bonita
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bonita.rule=Host(`bonita.localhost`)"
      - "traefik.http.routers.bonita.middlewares=bonita-cors@docker"
      - "traefik.http.middlewares.bonita-cors.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.bonita-cors.headers.accessControlExposeHeaders=*"
      - "traefik.http.middlewares.bonita-cors.headers.accessControlAllowOriginList=http://${SWAGGER_HOSTNAME}:${TRAEFIK_PORT}"
      - "traefik.http.middlewares.bonita-cors.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.bonita-cors.headers.addVaryHeader=true"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://bonita.localhost/bonita" ]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
