type: object
properties:
  id:
    description: "id of the application page item"
    type: integer
    format: int64
  token:
    description: "token use to access the page using a URL : ../appName/pageToken/"
    type: string
  applicationId:
    description: "id of the application related to this page"
    type: integer
    format: int64
  pageId:
    description: "id of the custom page to display"
    type: integer
    format: int64
example:
  id: 9876
  token: "myPage"
  applicationId: 1234
  pageId: 5678