type: object
properties:
  createdBy:
    description: Author user ID
    format: string
  creationDate:
    description: creation date of the application
    type: string
  description:
    description: description of the application
    type: string
  displayName:
    description: display name of the application
    type: string
  homePageId:
    description: id of the application page used as the home page
    format: string
  id:
    description: id of the application
    format: string
  lastUpdateDate:
    description: last update date of the application
    type: string
  profileId:
    description: profile authorized to access this application
    format: string
  token:
    description: token of the application used to build the application URL
    type: string
  updatedBy:
    description: Last updating user ID
    format: string
  version:
    description: version of the application
    type: string
example:
  id: "305"
  creationDate: "1411548289900"
  iconPath: ""
  createdBy": "1"
  profileId: "2"
  description: "My application description"
  token: "myapp"
  state: "DEACTIVATED"
  displayName: "My app"
  updatedBy: "1"
  lastUpdateDate: "1411548289900"
  version: "1.0"
  homePageId: "-1"