version: '3'
services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "${TRAEFIK_PORT}:80"
      # The Web UI (enabled by --api.insecure=true)
      - "${TRAEFIK_ADMIN_PORT}:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  swagger-ui:
    image: swaggerapi/swagger-ui
    labels:
      - "traefik.http.routers.swagger.rule=Host(`${SWAGGER_HOST}`)"
      - "traefik.http.services.swagger.loadbalancer.server.port=8080"
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./dist:/openapi

  redoc-ui:
    image: redocly/redoc
    labels:
      - "traefik.http.routers.redoc.rule=Host(`${REDOC_HOST}`)"
      - "traefik.http.services.redoc.loadbalancer.server.port=80"
    environment:
      - SPEC_URL=spec/openapi.yml
    volumes:
      - ./dist/openapi.yaml:/usr/share/nginx/html/spec/openapi.yml

  bonita:
    image: bonita:7.15.0
    labels:
      - "traefik.http.routers.bonita.rule=Host(`${BONITA_HOST}`)"
      - "traefik.http.routers.bonita.middlewares=bonita-cors@docker"
      - "traefik.http.middlewares.bonita-cors.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.bonita-cors.headers.accessControlExposeHeaders=*"
      - "traefik.http.middlewares.bonita-cors.headers.accessControlAllowOriginList=http://swagger.localhost"
      - "traefik.http.middlewares.bonita-cors.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.bonita-cors.headers.addVaryHeader=true"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://bonita.localhost/bonita" ]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
