- name: Ensures folder [{{bonita_folder}}] exists
  file: path={{bonita_folder}} state=directory owner={{bonita_user}} group={{bonita_group}}

- name: Copy files to [{{bonita_folder}}]
  copy:
    src: "{{ local_folder }}"
    dest: "{{ bonita_folder }}"
    owner: "{{ bonita_user }}"
    group: "{{ bonita_group }}"

- name: "Set folder {{ bonita_folder }} readable"
  file:
    path: "{{ bonita_folder }}"
    owner: "{{ bonita_user }}"
    group: "{{ bonita_group }}"

- name: Ensures folder [{{bonita_folder}}/files/dist] exists
  file: path={{bonita_folder}}/files/dist state=directory owner={{bonita_user}} group={{bonita_group}}

- name: "Get bonita-openapi-{{ open_api_release }}.yaml"
  get_url:
    url: "https://github.com/bonitasoft/bonita-openapi/releases/download/{{ open_api_release }}/bonita-openapi-{{ open_api_release }}.yaml"
    dest: "{{ bonita_folder }}/files/dist/openapi.yaml"
    owner: "{{ bonita_user }}"
    group: "{{ bonita_group }}"

- name: "Get bonita-postman-collection-{{ open_api_release }}.yaml"
  get_url:
    url: "https://github.com/bonitasoft/bonita-openapi/releases/download/{{ open_api_release }}/bonita-postman-collection-{{ open_api_release }}.json"
    dest: "{{ bonita_folder }}/files/dist/postman.json"
    owner: "{{ bonita_user }}"
    group: "{{ bonita_group }}"

