- name: Ensures folder [{{bonita_folder}}] exists
  file: path={{bonita_folder}} state=directory owner={{bonita_user}} group={{bonita_group}}

- name: Copy files to [{{bonita_folder}}]
  copy:
    src: "{{ local_folder }}"
    dest: "{{ bonita_folder }}"
    owner: "{{ bonita_user }}"
    group: "{{ bonita_group }}"

- name: "Set folder {{ bonita_folder }} readable"
  file:
    path: "{{ bonita_folder }}"
    owner: "{{ bonita_user }}"
    group: "{{ bonita_group }}"

- name: Pip install docker for Ansible's docker_login and docker_service modules
  pip:
    name: ["docker", "docker-compose"]

- name: Start Docker compose
  docker_compose:
    project_src: "{{ bonita_folder }}/"
    files: "docker-compose.yml"
    env_file: "docker.env"
    state: present
    pull: yes
    debug: yes
    project_name: runtime
    recreate: always
    remove_orphans: yes
    remove_volumes: yes
    remove_images: local
