- name: Pip install docker for Ansible's docker_login and docker_service modules
  pip:
    name: ["docker", "docker-compose"]

- name: Shutdown Bonita Platform (Database and Runtime), if already running
  docker_compose:
    project_src: "{{ bonita_folder }}/files/"
    files: "docker-compose.yaml"
    state: absent
    stopped: yes
    remove_orphans: yes
    remove_volumes: yes
    remove_images: local
    debug: yes
    project_name: runtime


- name: Start Docker compose
  docker_compose:
    project_src: "{{ bonita_folder }}/files/"
    files: "docker-compose.yaml"
    state: present
    pull: yes
    debug: yes
    project_name: runtime
    recreate: always
    remove_orphans: yes
    remove_volumes: yes
    remove_images: local

- name: Site available
  ansible.builtin.debug:
    msg: "Open API demo site: http://{{ publicDnsName }}:8084"